version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /dataproxy_sdk/python
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /docs
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
